### ISSUE TITLE
URI is not valid and cannot be converted into a string

### ISSUE THREAD

**Issue by raulsinapsis** [bitExpert/magento2-force-login#168] opened 2019-10-01 08:28 UTC
Details explained here https://magento.stackexchange.com/questions/291320/magento2-uri-is-not-valid-and-cannot-be-converted-into-a-string

Magento 2.3.2

Error message: **URI is not valid and cannot be converted into a string**

Trace

    #0 \MAGENTO_ROOT/vendor\/zendframework\/zend-http\/src\/Header\/AbstractLocation.php(102): Zend\\Uri\\Uri->toString()\n
    #1 \MAGENTO_ROOT/vendor\/zendframework\/zend-http\/src\/Header\/AbstractLocation.php(137): Zend\\Http\\Header\\AbstractLocation->getUri()\n
    #2 \MAGENTO_ROOT/vendor\/zendframework\/zend-http\/src\/PhpEnvironment\/Response.php(96): Zend\\Http\\Header\\AbstractLocation->toString()\n
    #3 \MAGENTO_ROOT/generated\/code\/Magento\/Framework\/App\/Response\/Http\/Interceptor.php(310): Zend\\Http\\PhpEnvironment\\Response->sendHeaders()\n
    #4 \MAGENTO_ROOT/vendor\/zendframework\/zend-http\/src\/PhpEnvironment\/Response.php(126): Magento\\Framework\\App\\Response\\Http\\Interceptor->sendHeaders()\n
    #5 \MAGENTO_ROOT/generated\/code\/Magento\/Framework\/App\/Response\/Http\/Interceptor.php(336): Zend\\Http\\PhpEnvironment\\Response->send()\n
    #6 \MAGENTO_ROOT/vendor\/magento\/framework\/HTTP\/PhpEnvironment\/Response.php(39): Magento\\Framework\\App\\Response\\Http\\Interceptor->send()\n
    #7 \MAGENTO_ROOT/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\HTTP\\PhpEnvironment\\Response->sendResponse()\n
    #8 \MAGENTO_ROOT/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\App\\Response\\Http\\Interceptor->___callParent('sendResponse', Array)\n
    #9 \MAGENTO_ROOT/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\Response\\Http\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n
    #10 \MAGENTO_ROOT/generated\/code\/Magento\/Framework\/App\/Response\/Http\/Interceptor.php(117): Magento\\Framework\\App\\Response\\Http\\Interceptor->___callPlugins('sendResponse', Array, Array)\n
    #11 \MAGENTO_ROOT/vendor\/magento\/framework\/App\/Bootstrap.php(259): Magento\\Framework\\App\\Response\\Http\\Interceptor->sendResponse()\n
    #12 \MAGENTO_ROOT/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n
    #13 {main}","url":"\/customer\/account\/loginPost\/","script_name":"\/index.php"}

I have checked & found a plugin in your module **app/code/BitExpert/ForceCustomerLogin/Plugin/AfterLoginPlugin.php**, so I suspect that `$targetUrl = $this->session->getAfterLoginReferer();` is setting some bad encoded url to redirect

Any fix for this? May we just disable that plugin in your module?

**Comment by shochdoerfer** [comment] 2019-10-01 10:05
Thanks for the bug report. Any chance you can figure out which page the user was on before trying to logging in?

I'd assume you could disable the plugin but then redirects to the page the user was before won't work anymore. If that's fine for you, go ahead. As an alternative wrap that code in a try/catch block, log the exception and the URL and redirect the user to `$this->defaultTargetUrl`. Since no one else reported a similar issue so far, this might be an issue depending on your setup. I'd love to know what the root cause is ;)

**Comment by websharp** [comment] 2019-10-01 11:25
@raulsinapsis Did you change the configuration (target url) in the following setting section?

https://github.com/bitExpert/magento2-force-login/blob/master/resources/ui_step_00.png

**Comment by shochdoerfer** [comment] 2019-11-01 08:47
@raulsinapsis were you able to figure out what causes the problem? Are you able to log the what value $targetUrl has when this happens?

**Comment by shochdoerfer** [comment] 2019-12-16 20:33
@raulsinapsis any update on that matter?

**Comment by websharp** [comment] 2020-10-21 08:57
@raulsinapsis Closing this issue for now, Feel free to (re)open the issue, if the problem remains

**Closed by websharp** 2020-10-21 08:57 UTC
