### ISSUE TITLE
incompatible with community Edition 2.4.0

### ISSUE THREAD

**Issue by haxim0r** [bitExpert/magento2-force-login#194] opened 2020-09-10 06:24 UTC
Due to magento framework 102 requirement which breaks Magento Upgrade from 2.3 to 2.4. 2.4 requires magento framework 103.*

**Comment by shochdoerfer** [comment] 2020-09-10 06:56
Duplicate of #190. There's already a PR open, see #191 - just could not yet find the time to test and merge ;(

**Closed** 2020-09-10 06:56 UTC
