### ISSUE TITLE
Magento2 Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'block', attribute 'class': [facet 'pattern'] The value 'bitExpert\ForceCustomerLogin\Block\Adminhtml\Manage\Create' is not accepted by the pattern '[A-Z][a-zA-Z\d]*(\\[A-Z][a-zA-Z\d]*)*'.

### ISSUE THREAD

**Issue by maxcamo** [bitExpert/magento2-force-login#94] opened 2017-12-01 08:58 UTC
Hello,

i have installed the module on a plain 2.2

1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'block', attribute 'class': [facet 'pattern'] The value 'bitExpert\ForceCustomerLogin\Block\Adminhtml\Manage\Create' is not accepted by the pattern '[A-Z][a-zA-Z\d]*(\\[A-Z][a-zA-Z\d]*)*'.
Line: 124

Element 'block', attribute 'class': 'bitExpert\ForceCustomerLogin\Block\Adminhtml\Manage\Create' is not a valid value of the atomic type 'blockClassType'.
Line: 124

Element 'block', attribute 'class': [facet 'pattern'] The value 'bitExpert\ForceCustomerLogin\Block\Adminhtml\Manage\Create\Submit' is not accepted by the pattern '[A-Z][a-zA-Z\d]*(\\[A-Z][a-zA-Z\d]*)*'.
Line: 125

Element 'block', attribute 'class': 'bitExpert\ForceCustomerLogin\Block\Adminhtml\Manage\Create\Submit' is not a valid value of the atomic type 'blockClassType'.
Line: 125

Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'block', attribute 'class': [facet 'pattern'] The value 'bitExpert\ForceCustomerLogin\Block\Adminhtml\Manage\Create' is not accepted by the pattern '[A-Z][a-zA-Z\d]*(\\[A-Z][a-zA-Z\d]*)*'.
Line: 124

Element 'block', attribute 'class': 'bitExpert\ForceCustomerLogin\Block\Adminhtml\Manage\Create' is not a valid value of the atomic type 'blockClassType'.
Line: 124

Element 'block', attribute 'class': [facet 'pattern'] The value 'bitExpert\ForceCustomerLogin\Block\Adminhtml\Manage\Create\Submit' is not accepted by the pattern '[A-Z][a-zA-Z\d]*(\\[A-Z][a-zA-Z\d]*)*'.
Line: 125

Element 'block', attribute 'class': 'bitExpert\ForceCustomerLogin\Block\Adminhtml\Manage\Create\Submit' is not a valid value of the atomic type 'blockClassType'.
Line: 125

**Comment by shochdoerfer** [comment] 2017-12-02 02:19
Duplicate of #93.

**Closed by shochdoerfer** 2017-12-02 02:19 UTC
