### ISSUE TITLE
Unable to access protected URLs when logged in 

### ISSUE THREAD

**Issue by adamj88** [bitExpert/magento2-force-login#69] opened 2017-05-04 08:12 UTC
I'm having trouble accessing protected pages after logging in when using 2.0.1 and Magento CE 2.1.6.

If I try to access homepage root on `/` I'm getting redirected to `/customer/account/login`, I can login then get redirected to `/customer/account/`, the customer dashboard.

Once logged in and trying to access the homepage again, I get a 302 redirect to `/customer/account/login` which 302 directs me back to `/customer/account/`.

I thought this may be down to the `customer/startup/redirect_dashboard` (Redirect Customer to Account Dashboard after Logging in) configuration being set to 1 however setting it to 0 has no change in behaviour at all.

Does anyone have any ideas what could be causing this?

**Comment by adamj88** [comment] 2017-05-08 10:02
@websharp have you had any experience of this issue or any ideas what may be causing this?

**Comment by websharp** [comment] 2017-05-08 16:56
Hi @adamj88 ,

so do you have a custom target url set in the administration? The handling of this is happening in the [after login plugin](https://github.com/bitExpert/magento2-force-login/blob/master/Plugin/AfterLoginPlugin.php), I need to look it up more to conclude the potential of misconception, but for the moment I am not clear of the cause of the side effect you describe.

**Comment by adamj88** [comment] 2017-05-08 17:21
Our target URL is set to `customer/account/login`.

We debugged it a bit further and round the event `customer_session_init` (https://github.com/bitExpert/magento2-force-login/blob/master/etc/events.xml#L15), was getting fired twice for some reason, in the first instance as a guest, and in the second as a logged in user.

To work around this we fired the `LoginRequiredOnCustomerSessionInitObserver` observer on a much earlier event: `controller_action_predispatch`.

We also injected `\Magento\Customer\Model\Session` into the observer as well and for the `isLoggedIn()` method.

I can put together a PR for this if required, but I'm not sure if this was an isolated incident - are you experiencing this too?

**Comment by websharp** [comment] 2017-06-12 06:06
Hi @adamj88 ,

I was not able to reproduce this issue. I checked on CE-2.1.7 (clean setup). Do you have any advanced caching systm running like Redis, Memcached or Varnish?

**Comment by adamj88** [comment] 2017-06-12 07:44
Hi @websharp 

Yes this was both with Varnish & Redis running, I'll push a copy of the work around to a fork when I get chance, see if it makes any sense.

**Comment by websharp** [comment] 2017-10-25 13:06
Hi @adamj88 ,

I will close this issue for now, but if you encounter the problem again, feel free to reopen. Maybe you want to try out the new release candidate for v2.3.0 first (https://github.com/bitExpert/magento2-force-login/releases/tag/v2.3.0-RC1).

Best Regards

**Closed by websharp** 2017-10-25 13:06 UTC
